<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <UseWPF Condition="'$(TargetFramework)' == 'net8.0-windows'">true</UseWPF>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <Title>ExcelMerge</Title>
    <Copyright>Copyright ©skanmera  2017</Copyright>
    <FileVersion>1.4.0.0</FileVersion>
    <AssemblyVersion>1.4.0.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetDiff\NetDiff\NetDiff.csproj" />
    <ProjectReference Include="..\SKCore\SKCore\SKCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NPOI" Version="2.7.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>
</Project>