<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Copyright>Copyright ©skanmera  2017</Copyright>
    <AssemblyName>ExcelMerge</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExcelMerge.Core\ExcelMerge.Core.csproj" />
    <ProjectReference Include="..\FastWpfGrid\FastWpfGrid\FastWpfGrid.csproj" />
    <ProjectReference Include="..\FastWpfGrid\WriteableBitmapEx\WriteableBitmapEx.Wpf.csproj" />
    <ProjectReference Include="..\SKCore\SKCore.Wpf\SKCore.Wpf.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.6.0" />
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.4.1" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.3" />
    <PackageReference Include="Unity" Version="5.11.10" />
    <PackageReference Include="YamlDotNet" Version="15.1.2" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>
  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>